### ISSUE TITLE
double click causes app crash

### ISSUE THREAD

**Issue by myleftfoot** [coolaj86/osx-wifi-volume-remote#2]
repro:
launch app
osx-wifi-volume-server 4040

navigate to url
double click on < or > button

actual:
crash 
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at ServerResponse.res.write (/usr/local/lib/node_modules/osx-wifi-volume-remote/node_modules/express/node_modules/connect/lib/middleware/compress.js:110:17)
    at ServerResponse.res.end (/usr/local/lib/node_modules/osx-wifi-volume-remote/node_modules/express/node_modules/connect/lib/middleware/compress.js:116:14)
    at ServerResponse.res.send (/usr/local/lib/node_modules/osx-wifi-volume-remote/node_modules/express/lib/response.js:152:8)
    at ServerResponse.res.json (/usr/local/lib/node_modules/osx-wifi-volume-remote/node_modules/express/lib/response.js:194:15)
    at ServerResponse.res.send (/usr/local/lib/node_modules/osx-wifi-volume-remote/node_modules/express/lib/response.js:120:21)
    at respond (/usr/local/lib/node_modules/osx-wifi-volume-remote/app.js:57:11)
    at null._onTimeout (/usr/local/lib/node_modules/osx-wifi-volume-remote/lib/osascript-vol-ctrl.js:115:9)
    at Timer.listOnTimeout (timers.js:110:15)

expected:
 no crash

**Comment by ncob** [comment]
Additionally, the app crashes (with the identical error message), when attempting to set the same volume level twice in a row.

In other words, if the machine's volume is set to 25%, and a user taps the '25' button in the UI, the app will crash.

**Comment by coolaj86** [comment]
Merged in branch over at https://git.daplie.com/coolaj86/osx-wifi-volume-remote

Published as version v1.0.4
